[[pages]]
path = "pages/Home.py"
name = "Home"

[[pages]]
path = "pages/pnl_report.py"
name = "Position & P/L Report"

[[pages]]
path = "pages/Risk.py"
name = "Risk Report"

[[pages]]
path = "pages/Historicals.py"
name = "Historicals Report"

[[pages]]
path = "pages/Emailer.py"
name = "Emailer"

[[pages]]
path = "pages/MKRGPT.py"
name = "MKRGPT"

[[pages]]
path = "pages/Calendar.py"
name = "Calendar"

[[pages]]
path = "pages/Resources.py"
name = "Resources"